import CalorieTracker from './calorieTracker'
import { Meal, Workout } from './Items'
import { Modal, Collapse } from 'bootstrap'
import '@fortawesome/fontawesome-free/js/all'
import './css/bootstrap.css'
import './css/style.css'
